server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 172.168.1.1
    virtual-host: leyou
    username: leyou
    password: leyou
  redis:
    host: 172.168.1.1
    password: 123456



leyou:
  sms:
    accessKeyId: LTAI4GGn1S2omdsds78wdsDF8P # 你自己的accessKeyId
    accessKeySecret: daA132dsafI7Yidsa6782FyykA # 你自己的AccessKeySecret
    signName: leyouMall # 签名名称
    verifyCodeTemplate: SMS_184326522 # 模板名称
