server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 39.97.180.158
    virtual-host: leyou
    username: leyou
    password: leyou
  redis:
    host: 39.97.180.158
    password: jcl5412415845



leyou:
  sms:
    accessKeyId: LTAI4GGn1S2omVye6Vw5DF8P # 你自己的accessKeyId
    accessKeySecret: daA1Vr0795I7YiwdKTAreuegkFyykA # 你自己的AccessKeySecret
    signName: leyouMall # 签名名称
    verifyCodeTemplate: SMS_189521122 # 模板名称
