server:
  port: 8087
spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

leyou:
  jwt:
    secret: ea61b46dse2@leyou@9ds966@leyou@33da # 登录校验的密钥
    pubKeyPath: E:\\知识学习\\乐优商城-11月版\\leyou\\day17-授权中心\\rsa.pub # 公钥地址
    priKeyPath: E:\\知识学习\\乐优商城-11月版\\leyou\\day17-授权中心\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
